export const MAX_PRACTICAL_GUARANTEED_KO_HITS = 3;
export const MAX_PRACTICAL_DEFENSIVE_KO_HITS = 3;
export const MAX_OPTIMIZATION_CANDIDATES = 12;
export const MAX_BENCHMARKS_PER_AXIS = 2;
export const MAX_USAGE_MOVES_PER_SIDE = 4;
export const MAX_ALTERNATE_USAGE_MOVES = 2;
export const MAX_REPLACEMENT_SLOTS_PER_MOVE = 4;
export const MAX_ALTERNATE_MOVE_LOADOUTS =
  MAX_ALTERNATE_USAGE_MOVES * MAX_REPLACEMENT_SLOTS_PER_MOVE;
export const MAX_ALTERNATE_ITEM_LOADOUTS = 2;
export const MAX_BREAKPOINTS_PER_MOVE_NATURE = 6;
export const MAX_COMBINATION_FRONTIER = 40;
export const MAX_FINAL_SEARCH_FRONTIER = 160;
export const MIN_MEANINGFUL_KO_CHANCE_GAIN = 6.25;
export const KO_CHANCE_EPSILON = 0.01;
